#!/usr/bin/env ruby

VERSIONS = %w[
  1.8.7 
  1.9.3
  2.0.0
  2.1.0
  2.2.0
]

RUBY = "ruby"

BITCLUST_BASE = "/var/rubydoc/bitclust"
BITCLUST = "#{BITCLUST_BASE}/bin/bitclust"
BITCLUST_LIB_DIR = "#{BITCLUST_BASE}/lib"

DOC_BASE = "/var/rubydoc/doctree"
REF_BASE = "#{DOC_BASE}/refm"

def setup_db(version)
  db = "#{REF_BASE}/db-#{version}"
  `rm -rf #{db}`
  `#{RUBY} -I#{BITCLUST_LIB_DIR} #{BITCLUST} -d #{db} init version=#{version} encoding=utf-8`
  `#{RUBY} -I#{BITCLUST_LIB_DIR} #{BITCLUST} -d #{db} update --stdlibtree=#{REF_BASE}/api/src`
  `#{RUBY} -I#{BITCLUST_LIB_DIR} #{BITCLUST} -d #{db} --capi update #{REF_BASE}/capi/src/*`
  puts "#{version} is done"
end

if !File.directory?(BITCLUST_BASE)
  `git clone https://github.com/rurema/bitclust.git #{BITCLUST_BASE}`
end

if !File.directory?(DOC_BASE)
  `git clone https://github.com/rurema/doctree.git #{DOC_BASE}`
end

Dir.chdir(DOC_BASE) do
  system "git pull --rebase"
end

VERSIONS.reverse_each do |version|
  setup_db(version)
end
