#!/usr/bin/env ruby

VERSIONS = %w[
  2.2.0
  2.3.0
  2.4.0
]

RUBY = "ruby"

BITCLUST_BASE = "/var/rubydoc/bitclust"
BITCLUST = "#{BITCLUST_BASE}/bin/bitclust"
BITCLUST_LIB_DIR = "#{BITCLUST_BASE}/lib"
BITCLUST_DATA = "#{BITCLUST_BASE}/data/bitclust"
TEMPLATE="#{BITCLUST_DATA}/template.offline"
CATALOG="#{BITCLUST_DATA}/catalog"

REF_BASE = "/var/rubydoc/doctree/refm"

DOC_ROOT = "/var/www/docs.ruby-lang.org/shared/public/ja"

def create_document(version)
  system(RUBY, "-I#{BITCLUST_LIB_DIR}",
         BITCLUST,
         "--database=#{REF_BASE}/db-#{version}",
         "statichtml",
         "--outputdir=/var/rubydoc/tmp/#{version}",
         "--templatedir=#{TEMPLATE}",
         "--catalog=#{CATALOG}",
         "--fs-casesensitive",
         "--canonical-base-url=https://docs.ruby-lang.org/ja/latest/",
         "--tracking-id=UA-620926-3",
         "--quiet")
  system("rsync", "-acvi", "--no-times", "--delete", "/var/rubydoc/tmp/#{version}", DOC_ROOT) or raise
  system("rm", "-rf", "/var/rubydoc/tmp/#{version}") or raise
  system('./system/fastly-purge-key', '--soft', "ja/#{version}")
  puts "#{version} is done."
end

VERSIONS.reverse_each do |version|
  create_document(version)
end

Dir.chdir(DOC_ROOT) do
  system("unlink", "latest")
  system("ln", "-s", "-f", VERSIONS.max, "latest")
end
