#!/usr/bin/env ruby

require 'fileutils'

VERSIONS = %w[
  3.0
  3.1
  3.2
  3.3
  3.4
]

RUBY = "ruby"

BITCLUST_BASE = "/var/rubydoc/bitclust"
BITCLUST = "#{BITCLUST_BASE}/bin/bitclust"
BITCLUST_LIB_DIR = "#{BITCLUST_BASE}/lib"

DOC_BASE = "/var/rubydoc/doctree"
REF_BASE = "refm" # was "#{DOC_BASE}/refm"

GENERATED_DOCUMENTS_BASE = "/var/rubydoc/generated-documents"

def setup_db(version)
  Dir.chdir(DOC_BASE) do
    db = "#{REF_BASE}/db-#{version}"
    FileUtils.rm_rf db
    system(*%W"#{RUBY} -I#{BITCLUST_LIB_DIR} #{BITCLUST} -d #{db} init version=#{version} encoding=utf-8")
    system(*%W"#{RUBY} -I#{BITCLUST_LIB_DIR} #{BITCLUST} -d #{db} update --stdlibtree=#{REF_BASE}/api/src")
    system(*%W"#{RUBY} -I#{BITCLUST_LIB_DIR} #{BITCLUST} -d #{db} --capi update" + Dir.glob("#{REF_BASE}/capi/src/*"))
    puts "#{version} is done"
  end
end

if !File.directory?(BITCLUST_BASE)
  system(*%W"git clone --depth 1 https://github.com/rurema/bitclust.git #{BITCLUST_BASE}")
end

if !File.directory?(DOC_BASE)
  system(*%W"git clone --depth 1 https://github.com/rurema/doctree.git #{DOC_BASE}")
end


if !File.directory?(GENERATED_DOCUMENTS_BASE)
  system(*%W"git clone --depth 1 https://github.com/rurema/generated-documents.git #{GENERATED_DOCUMENTS_BASE}")
end

Dir.chdir(GENERATED_DOCUMENTS_BASE) do
  system(*%w"git fetch origin")
  system(*%w"git reset origin/main --hard")
end

Dir.glob("#{GENERATED_DOCUMENTS_BASE}/db/db-*") do |db|
  src = db
  dst = "#{DOC_BASE}/"#{REF_BASE}/#{File.basename(db)}"
  FileUtils.rm_rf(dst) if File.directory?(dst)
  system(*%w"ln -snf #{src} #{dst}")
end

exit

Dir.chdir(BITCLUST_BASE) do
  system(*%w"git fetch origin")
  system(*%w"git reset origin/master --hard")
end

Dir.chdir(DOC_BASE) do
  system(*%w"git fetch origin")
  system(*%w"git reset origin/master --hard")
end

VERSIONS.reverse_each do |version|
  setup_db(version)
end
