#!/usr/bin/env ruby

VERSIONS = %w[
  1.8.7
  1.9.3
  2.0.0
  2.1.0
  2.2.0
]

DOC_ROOT = "/var/www/docs.ruby-lang.org/shared/en"

def create_document(version)
  system("rake", "update:#{version}")
  system("rake", "rdoc:clobber_en/#{version}")
  system("rake", "rdoc:en/#{version}")
  `rm -rf #{DOC_ROOT}/#{version}`
  `mv #{version} #{DOC_ROOT}`
  puts "#{version} is done."
end

VERSIONS.reverse_each do |version|
  create_document(version)
end
