#!/usr/bin/env ruby

VERSIONS = %w[
  2.5.0
  2.6.0
  2.7.0
  master
]

DOC_ROOT = ENV.fetch('DOC_ROOT', "/var/www/docs.ruby-lang.org/shared/public/en")

Dir.chdir(File.join(__dir__, '..'))

def create_document(version)
  system("bundle", "exec", "rake", "update:#{version}") or raise
  system("bundle", "exec", "rake", "rdoc:clobber_en/#{version}") or raise
  system("bundle", "exec", "rake", "rdoc:en/#{version}") or raise
  system("rsync", "-acvi", "--no-times", "--delete", version, DOC_ROOT) or raise
  system("rm", "-rf", version) or raise
  system('./system/fastly-purge-key', '--soft', "en/#{version}")
  puts "#{version} is done."
end

VERSIONS.reverse_each do |version|
  create_document(version)
end
