#! /bin/zsh
BASE_DIR=/var/rubydoc
APP_DIR=$BASE_DIR/rurema-search
CURRENT_DIR=$APP_DIR/current
SHARED_DIR=$APP_DIR/shared

RUBY=~rurema/.rbenv/shims/ruby
BUNDLE=~rurema/.rbenv/shims/bundle
DOC_BASE=$BASE_DIR/doctree/refm
BITCLUST_LIB_DIR=$BASE_DIR/bitclust/lib

cd ${CURRENT_DIR}
$BUNDLE exec $RUBY -I${BITCLUST_LIB_DIR} ${CURRENT_DIR}/bin/bitclust-indexer ${DOC_BASE}/db-*
