#! /bin/zsh
SCRIPT_DIR=$(dirname $0)
BASE_DIR=/var/rubydoc
APP_DIR=$BASE_DIR/rurema-search
CURRENT_DIR=$APP_DIR/current
SHARED_DIR=$APP_DIR/shared

RUBY=ruby
BUNDLE=bundle
DOC_BASE=$BASE_DIR/doctree/refm
BITCLUST_LIB_DIR=$BASE_DIR/bitclust/lib

set -e
cd ${CURRENT_DIR}
$BUNDLE exec $RUBY -I${BITCLUST_LIB_DIR} ${CURRENT_DIR}/bin/bitclust-indexer ${DOC_BASE}/db-*
cd -
${SCRIPT_DIR}/fastly-purge-key --soft rurema-search-app || :
