#! /bin/zsh
BASE_DIR=/var/rubydoc
APP_DIR=$BASE_DIR/rurema-search

RUBY=~rurema/.rbenv/versions/2.1.0/bin/ruby
DOC_BASE=$BASE_DIR/doctree/refm
BITCLUST_LIB_DIR=$BASE_DIR/bitclust/lib

rm -rf ${APP_DIR}/groonga-database
mkdir -p ${APP_DIR}/groonga-database

cd ${APP_DIR}
rbenv version
bundle exec $RUBY -I${BITCLUST_LIB_DIR} ${APP_DIR}/bin/bitclust-indexer ${DOC_BASE}/db-*

chown -R rurema:rurema ${APP_DIR}/groonga-database
chmod -R g+w ${APP_DIR}/groonga-database

chown -R rurema:rurema ${APP_DIR}/var/lib/suggest
chmod -R g+w ${APP_DIR}/var/lib/suggest
